### ISSUE TITLE
Clearing body style is both hard to discover and very destructive

### ISSUE THREAD

**Issue by bradley-dotnet** [vtllr/ngx-virtual-keyboard#11]
The `close` method of the virtual keyboard destroys the `style` attribute of `body`. 

This causes very difficult to find bugs when site behavior already has a `style` on the `body` (for example, setting `height: 100%`). This behavior should be made less destructive, only removing (or even better _resetting_) the attributes changed by the virtual keyboard.

**Comment by vtllr** [comment]
Thanks @bradley-dotnet. You're right. I will clean that in the next push or feel free to submit your own PR. The module require some refactoring I guess.

**Comment by vtllr** [comment]
See https://github.com/vtllr/ngx-virtual-keyboard/commit/b78b5a42eec5fa8f783323b69dc212905465b018#diff-1219924544088b0dbd4a976e12e76395
