### ISSUE TITLE
Missing keyboard 

### ISSUE THREAD

**Issue by Alex66955** [vtllr/ngx-virtual-keyboard#14]
Implemented like in description but nothing happened, when input field was focused.
Is there anything missing?

Angular: 4
NPM:  3.10.10

**Comment by vtllr** [comment]
It should work.
Could you provide a code extract, please? Is your code similar to [the demo](https://github.com/vtllr/ngx-virtual-keyboard/blob/master/demo/form/form.component.pug)?

**Comment by Alex66955** [comment]
Okay. New day and it works. 
Thanks for fast response and sorry for useless issue ;)

**Comment by vtllr** [comment]
Happy to know it! Enjoy typing so :)
