### ISSUE TITLE
Fails ng build

### ISSUE THREAD

**Issue by drullo** [vtllr/ngx-virtual-keyboard#18]
When building an Angular-CLI app that uses ngx-virtual-keyboard using 'ng build --prod --aot', it fails with the following errors.

ERROR in ng:///.../node_modules/ngx-virtual-keyboard/dist/ngx-virtual-keyboard.component.d.ts.NgxVirtualKeyboardComponent.html (3,8
): Property 'special' is private and only accessible within class 'NgxVirtualKeyboardComponent'.
ERROR in ng:///.../node_modules/ngx-virtual-keyboard/dist/ngx-virtual-keyboard.component.d.ts.NgxVirtualKeyboardComponent.html (7,1
6): Property 'getColSize' is private and only accessible within class 'NgxVirtualKeyboardComponent'.
ERROR in ng:///.../node_modules/ngx-virtual-keyboard/dist/ngx-virtual-keyboard.component.d.ts.NgxVirtualKeyboardComponent.html (3,8
): Property 'special' is private and only accessible within class 'NgxVirtualKeyboardComponent'.
ERROR in ng:///.../node_modules/ngx-virtual-keyboard/dist/ngx-virtual-keyboard.component.d.ts.NgxVirtualKeyboardComponent.html (7,1
6): Property 'getColSize' is private and only accessible within class 'NgxVirtualKeyboardComponent'.

**Comment by vtllr** [comment]
I have built the module with Webpack. I will try today and push a fix.
Thanks for highlighting this issue :)

**Comment by drullo** [comment]
Thanks @vtllr !  Nice keyboard!

In the meantime, I resolved the issue on my end by manually editing your typescript to remove the 'private' modifier on the conflicts.  Incidentally, the existing code does build without errors if you don't use the --prod or --aot.  But for production code, I need to use those switches.

**Comment by vtllr** [comment]
@drullo Fixed. Could you try 1.0.53?

**Comment by drullo** [comment]
1.0.53 fixed it.  Thank you!

**Comment by vtllr** [comment]
Thanks for your feedback buddy! have a great day
