### ISSUE TITLE
Where's the spacebar??

### ISSUE THREAD

**Issue by drullo** [vtllr/ngx-virtual-keyboard#19]
I like this keybaord.  But why is there no spacebar?  Is there a way to enable it, and why would it not be enabled by default?

**Comment by vtllr** [comment]
Hey @drullo,
Have you tried to use the layout "extendedKeyboard"? Feel free to check default layouts [here](https://github.com/vtllr/ngx-virtual-keyboard/blob/master/lib/layouts.ts)

**Comment by drullo** [comment]
Yes, actually switching to the extended layout did resolve the issue.  I was using the sample code on npmjs.org.  Once I realized that it was just a simple layout changed, that resolved the issue.  Thank you!

**Comment by vtllr** [comment]
Awesome! Happy your are happy with this module :) Can we close the issue?
