### ISSUE TITLE
Backspace key does not fire keyup event

### ISSUE THREAD

**Issue by drullo** [vtllr/ngx-virtual-keyboard#21]
I have a search text field bound to ngx-virtual-keyboard.  I'm listening to the keyup event on the input field and it triggers data filtering in my app.  However, the backspace key seems to not fire the keyup event, thus the displayed data does not get updated.  This problem does not occur when using a physical keyboard, only when using the backspace key on the virtual keyboard.

**Comment by vtllr** [comment]
You're right. The value will be updated if you enter one more character. Let me debug that this afternoon :) I will push a new version today.

**Comment by vtllr** [comment]
Should be fixed with 1.0.54 :) Enjoy!

**Comment by drullo** [comment]
Unfortunately, I'm seeing the same behavior with 1.0.54.  Also just noticed that the spacebar has the same issue.

**Comment by vtllr** [comment]
I'm sorry but I can't replicate. Is your input type search?

**Comment by drullo** [comment]
My input type was text.  But I just tried search as well.  Got the same result.

**Comment by vtllr** [comment]
@drullo Is that issue still an issue? Could you update to 1.0.56? Thanks!

**Comment by vtllr** [comment]
I'm closing the issue. Open again if needed
